# Generated by Django 4.2.3 on 2023-10-29 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter album name. If the song you are publishing has no album name, type 'Unknown' or 'Unknown album'", max_length=100)),
                ('album_image', models.FileField(blank=True, null=True, upload_to='albums')),
                ('record_label', models.CharField(blank=True, max_length=100, null=True)),
                ('album_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='artists')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='separate words with dashes instead of spaces', max_length=100)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='unknown-track', max_length=100)),
                ('short_description', models.TextField(blank=True, help_text='A short description about the song', max_length=1000)),
                ('audio_file', models.FileField(upload_to='songs')),
                ('audiomak_link', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField(null=True)),
                ('notification', models.BooleanField(default=False, verbose_name='Notify your subscribers about this song (Required)')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.genre')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
